avatar: /images/avatar.png # 网站 Logo
# background: https://i.loli.net/2019/01/13/5c3aec85a4343.jpg # 既是博客的背景，又是文章默认头图
favicon:
  href: /favicon-32x32.png # 网站图标
  type: image/png # 图标类型，可能的值有(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

# 附加图标库 用于自定义字体 www.iconfont.cn 登录->创建项目->添加图标->获取链接
iconlib: # //at.alicdn.com/t/font_1038733_0xvrvpg9c0r.css

cdn: # 这里可以修改站点使用的库的CDN
  mdui:
    css: https://cdn.jsdelivr.net/npm/mdui@0.4.3/dist/css/mdui.min.css
    js: https://cdn.jsdelivr.net/npm/mdui@0.4.3/dist/js/mdui.min.js
  lazysizes:
    js: https://cdn.jsdelivr.net/npm/lazysizes@5.2.0/lazysizes.min.js
  highlight:
    css: https://cdn.jsdelivr.net/npm/highlight.js@10.0.2/styles/github.css
    js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.0.2/build/highlight.min.js
  disqusjs:
    css: https://cdn.jsdelivr.net/npm/disqusjs@1.2.6/dist/disqusjs.min.css
    js: https://cdn.jsdelivr.net/npm/disqusjs@1.2.6/dist/disqus.min.js
#  gitalk:
#    css: https://cdn.jsdelivr.net/npm/gitalk@1.5.0/dist/gitalk.min.css
#    js: https://cdn.jsdelivr.net/npm/gitalk@1.5.0/dist/gitalk.min.js
#  valine:
#    js: https://cdn.jsdelivr.net/npm/valine@1.3.9/dist/Valine.min.js
  # copy: https://cdn.jsdelivr.net/gh/xtaodada/xtaodada.github.io@0.0.2/copy.js

menu:
  回到首页:
    - /
    - icon-home
  文章归档:
    - /archives
    - icon-container
  # 关于博客:
  #   - /about.html
  #   - icon-info-circle
  我的朋友:
    - /friends.html

widgets:
  - toc
  - social
  - category
  - tagcloud
  - archive
  - recent_posts


maxTagcloud: 10 # 0 表示不限制

toc: true

social:
  哔哩哔哩:
    - https://space.bilibili.com/7686754
    - icon-bilibili
    - rgb(231, 106, 141)
    - rgba(231, 106, 141, .15)
  GitHub:
    - https://github.com/Dreace233
    - icon-github
    - rgb(25, 23, 23)
    - rgba(25, 23, 23, .15)
  知乎:
    - https://www.zhihu.com/people/ni-xiang-42-96/activities
    - icon-zhihu
    - rgb(30, 136, 229)
    - rgba(30, 136, 229, .15)
  Twitter:
    - https://twitter.com/Dreace520
    - icon-twitter
    - rgb(29, 161, 242)
    - rgba(29, 161, 242, .15)
  Steam:
    - https://steamcommunity.com/id/Dreace_Dreace/
    - icon-steam
    - rgb(37, 116, 196)
    - rgba(37, 116, 196, .15)

site_verification: # 向搜索引擎验证你对站点的所有权，用于向搜索引擎提交 sitemap 和管理站点被搜索引擎收录的情况。
  google:
  baidu:

analytics:
  tencent_site_id: 500701683

comment: disqusjs # 评论框，目前支持 gitalk,gitment,valine,disqus,disqusjs,changyan,livere,DiscussBot


disqusjs:
  shortname: dreace # 你的 Disqus shortname
  sitename: DreaceのBlog # 你站点的名称，将会显示在「评论基础模式」的 header 中；该配置应该和 Disqus Admin - Settings - General - Website Name 一致
  api: https://disqus.dreace.top/api/ # DisqusJS 请求的 API Endpoint，通常情况下你应该配置一个 Disqus API 的反代并填入反代的地址。你也可以直接使用 DISQUS 官方 API 的 Endpoint https://disqus.com/api/，或是使用SukkaW搭建的 Disqus API 反代 Endpoint https://disqus.skk.moe/disqus/。
  apikey:
    - wWzaLh1lIGm4TQtRW4PdoHfZtFBQE4bk7srIXB2J7zRbjZdsLXcboiHY0qHloPgs
    - 1OH6IP9AXbWa1lfMZfSJJCPiCEXUIk9GlNtTTuZ3iJQKyzdwvoWBYrfUm9hIlRDn
    # DisqusJS 向 API 发起请求时使用的 API Key，你应该在配置 Disqus Application 时获取了 API Key;DisqusJS 支持填入一个 包含多个 API Key 的 Array，在每次请求时会随机使用其中一个；如果你只需要填入一个 API Key，则可以填入 String 或 Array。
  admin: Dreace233 # 你的站点的 Disqus Moderator 的用户名（也就是你的用户名）。你可以在 Disqus - Settings - Account - Username 获取你的 Username
  adminLabel: 书记！ # 你想显示在 Disqus Moderator Badge 中的文字。该配置应和 Disqus Admin - Settings - Community - Moderator Badge Text 相同

copyright: '<strong>版权声明：</strong>本文采用 <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/cn/deed.zh" target="_blank">CC BY-NC-SA 3.0 CN</a> 协议进行许可'

beian:
  ICP: 蜀ICP备17035453号-1 #工信部备案号
  police:
    full: 川公网安备 51202202000022 号 #公安部备案
    number: 51202202000022
